### ISSUE TITLE
X and Q sounds

### ISSUE THREAD

**Issue by majoravery** [SteveMCarroll/PronouncingNamesForEnglishSpeakers#5]
First of all, great guide! 

I think these two lines might be a bit misleading:

> X is like a Sh sound (as in "Shot")
> Q is like a Ch sound (as in "China")

Not all X are pronounced like Sh, especially Xi- and Qi- sounds. For example xiong2 熊 has its X pronounced more like a S sound as in "Sister". Same goes for Q. Perhaps Xu and Qu would have a more appropriate Sh sound instead.

Personally don't know how many Xu- words there are compared to Xi-, but changing the lines like so is less misleading:

> Most X is like a Sh sound (as in "Shot")
> Some X is like a Sh sound (as in "Shot")
> Xu is like a Sh sound (as in "Shot")

What do you think?

**Comment by SteveMCarroll** [comment]
Can I ask where you learned your Chinese?   So far I'm sticking to the wikipedia Standard Chinese phonology page as my sort of default reference... Needless to say, I'm a software guy, and linguisitics is just my hobby.   But here's what they say about the X sound:

> 
<html>
<body>


[ɕ] | Similar to English sh, but with an alveolo-palatal (softer) pronunciation | 小/xiǎo | x | ㄒ | hs | See § Alveolo-palatal series.
-- | -- | -- | -- | -- | -- | --



</body>
</html>

> The alveolo-palatal consonants (pinyin j, q, x) are standardly pronounced [t͡ɕ, t͡ɕʰ, ɕ]. Some speakers realize them as palatalized dentals [t͡sʲ], [t͡sʰʲ], [sʲ]; this is claimed to be especially common among children and women,[1]:33 although officially it is regarded as substandard and as a feature specific to the Beijing dialect.[4]

so the sound represented by the ɕ symbol is what I'm trying to help English speakers make.  In the wikipedia rendering they suggest that the xiong variant with the s sound is not quite in the standard dialect and so my default principle of "keep it simple" suggests not to complicate it but I am VERY open to being shown I'm wrong.    If we did take a change like this though, I'd prefer to give a concrete example of where it is used instead of having to make the reader try to figure it out since we are approximating here.

Honestly, I found learning to distinguish the actual chinese X (ɕ) sound and the chinese SH (ʂ) sound ,neither of which are exactly the same as the english SH (ʃ), to be reasonably doable as an adult learner, but I think I'll be saving those for an advanced doc for people who really are into this stuff.

**Comment by majoravery** [comment]
I'm Singaporean Chinese :-) English is my first language, but I still speak it every day with my parents. I learnt it in 10 years of school growing up in Singapore, and we don't go in depth into linguistics so I don't understand much about the specific terms mentioned above, but ~I can give you some examples~. I found a section of a video that clearly pronounces the difference: https://www.youtube.com/watch?v=05BMKdxHjp8&t=228s

I didn't think what you stated was wrong–I was just suggesting maybe declaring X = Sh is inaccurate, hence my suggestion above.

**Comment by seanyeh** [comment]
X = Sh is not exact, but I think it's the closest match. I disagree that Xi is more like an 'S' sound (in standard Mandarin). You can hear an example of xiong2 in the first second of https://www.youtube.com/watch?v=kuruanWTfM4

**Comment by majoravery** [comment]
I see now that the differences mostly lie in accents–I was speaking on behalf of Mandarin Chinese speakers like Singapore and Taiwan. For example:

> Liu | sounds like "leeoh"

In China, this would be accurate. But Mandarin Chinese speakers pronounce this more like "lieu". In any case, I just thought I'd give my 2 cents, feel free to close this issue as you see fit.

**Comment by SteveMCarroll** [comment]
When this pandemic is finally really really for reals over and I can travel freely again, Singapore is very high on my list.   Tried to watch a Singaporean drama and definitely know from that experience that I have some listening practice to do before that trip. 
I think it's a really beautiful accent.   Thanks for your feedback, I'm gonna close this out.
